import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Libre_Franklin } from "next/font/google";
import { Rubik } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";

const libre = Libre_Franklin({
  subsets: ["latin"],
  display: "swap",
});

// const rubik = Rubik({
//   subsets: ["latin"],
//   display: "swap",
// });
//
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${libre.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
